"""Configuration, read once from the environment."""

import os
import secrets
from dataclasses import dataclass, field
from typing import Optional


class ConfigError(ValueError):
    """Raised when the environment does not describe a usable bridge."""


@dataclass
class Config:
    """Everything the bridge needs to run.

    ``abs_url`` and ``abs_token`` point at the Audiobookshelf server. ``device_token`` is the
    secret the eReader appends to the bridge URL; it is generated by this project and has
    nothing to do with any account on the manufacturer's store.
    """

    abs_url: str
    abs_token: str
    device_token: str = field(default_factory=lambda: secrets.token_urlsafe(24))
    public_url: Optional[str] = None
    library_id: Optional[str] = None
    timeout: float = 30.0

    def __post_init__(self):
        self.abs_url = self.abs_url.rstrip("/")
        if not self.abs_url.startswith(("http://", "https://")):
            raise ConfigError("audiobookshelf url must start with http:// or https://")
        if not self.abs_token:
            raise ConfigError("an audiobookshelf api token is required")
        if not self.device_token:
            raise ConfigError("device token must not be empty")
        if self.public_url:
            self.public_url = self.public_url.rstrip("/")

    @classmethod
    def from_env(cls, env=None):
        env = os.environ if env is None else env
        abs_url = env.get("KOBOBRIDGE_ABS_URL", "").strip()
        if not abs_url:
            raise ConfigError(
                "set KOBOBRIDGE_ABS_URL to your Audiobookshelf address, for example "
                "http://192.168.1.10:13378"
            )
        abs_token = env.get("KOBOBRIDGE_ABS_TOKEN", "").strip()
        if not abs_token:
            raise ConfigError(
                "set KOBOBRIDGE_ABS_TOKEN to an Audiobookshelf API token "
                "(Settings, Users, pick a user, API token)"
            )
        device_token = env.get("KOBOBRIDGE_DEVICE_TOKEN", "").strip()
        return cls(
            abs_url=abs_url,
            abs_token=abs_token,
            device_token=device_token or secrets.token_urlsafe(24),
            public_url=(env.get("KOBOBRIDGE_PUBLIC_URL", "").strip() or None),
            library_id=(env.get("KOBOBRIDGE_LIBRARY_ID", "").strip() or None),
            timeout=float(env.get("KOBOBRIDGE_TIMEOUT", "30")),
        )
